import {graphShell,mountGraph} from './global-graph.mjs';
import {subjectColorStyle as colorStyle} from './subject-colors.mjs';
import {readingPreferences,passageControls,wirePassageReading} from './passage-reading.mjs';
import {circularLayout} from './subject-graph.mjs';
import {recordFilename} from './record-file.mjs';
import {passageCitation} from './passage-citation.mjs';
import {loadCompressed} from './data.mjs';
import {escapeHtml as esc} from './text.mjs';
import {compareSelections,publicSelections,unlinkedPassage} from './subject-list.mjs';
import {relationKey} from './subject-relations.mjs';
const $=id=>document.getElementById(id),params=()=>new URLSearchParams(location.search);
let index,base,selected,epoch=0;const cache=new Map();
let thematicGroups=[];
let disposeGraph=()=>{};
function url(changes={}){const p=params();for(const [k,v] of Object.entries(changes))v===null||v===''?p.delete(k):p.set(k,v);return './subjects.html'+(p.size?'?'+p:'');}
function go(changes){history.pushState({},'',url(changes));return render();}
function directory(){
  const q=$('subject-query').value.toLowerCase(),thematic=params().get('order')!=='alphabetical';
  $('subject-order').value=thematic?'thematic':'alphabetical';
  const link=s=>`<a class="subject-label" style="${colorStyle(s)}" ${s.id===params().get('subject')?'aria-current="true"':''} href="${esc(url({subject:s.id,page:null,author:null,volume:null,availability:null}))}">${esc(s.name)} <small>(${s.selections??0})</small></a>`;
  let count=0;
  if(thematic){
    const byName=new Map(index.subjects.map(s=>[s.name,s]));
    $('subject-list').innerHTML=thematicGroups.map(group=>{
      const rows=group.subjects.map(name=>byName.get(name)).filter(s=>s&&(s.name.toLowerCase().includes(q)||group.title.toLowerCase().includes(q)));
      count+=rows.length;if(!rows.length)return '';
      return `<section class="subject-section" aria-labelledby="section-${esc(group.id)}"><h3 id="section-${esc(group.id)}">${esc(group.title)}</h3>${rows.map(link).join('')}</section>`;
    }).join('');
  }else{
    const rows=index.subjects.filter(s=>s.name.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));
    count=rows.length;$('subject-list').innerHTML=rows.map(link).join('');
  }
  $('subject-count').textContent=`${count} of ${index.subjects.length} subjects`;
}
async function record(id){if(cache.has(id))return cache.get(id);const promise=loadCompressed(new URL(`data/${encodeURIComponent(recordFilename(id))}`,base)).catch(e=>{cache.delete(id);throw e;});cache.set(id,promise);if(cache.size>20)cache.delete(cache.keys().next().value);return promise;}
function highlight(text,ranges){let result='',end=0;const merged=[];for(const r of [...ranges].sort((a,b)=>a.start-b.start)){if(merged.length&&r.start<=merged.at(-1).end)merged.at(-1).end=Math.max(merged.at(-1).end,r.end);else merged.push({...r});}for(const r of merged){result+=esc(text.slice(end,r.start))+`<mark>${esc(text.slice(r.start,r.end))}</mark>`;end=r.end;}return result+esc(text.slice(end));}
function getDraft(){try{return JSON.parse(localStorage.getItem('pi-subject-edits')||'{"format":1,"matches":{},"relationships":[]}');}catch{return {format:1,matches:{},relationships:[]};}}
function saveDraft(draft){localStorage.setItem('pi-subject-edits',JSON.stringify(draft));if($('decision-preview'))$('decision-preview').value=JSON.stringify(draft,null,2);$('editor-result').textContent='Saved in this browser. Export decisions and import them into the project to publish.';}
const graphMeasure=document.createElement('canvas').getContext('2d');
function graphLines(name){
  graphMeasure.font='14px "EB Garamond"';
  const lines=[];let line='';
  for(const word of name.split(/\s+/)){
    const next=line?line+' '+word:word;
    if(graphMeasure.measureText(next).width<=122){line=next;continue;}
    if(line)lines.push(line);line='';
    for(const letter of word){if(line&&graphMeasure.measureText(line+letter).width>122){lines.push(line);line='';}line+=letter;}
  }
  if(line)lines.push(line);return lines;
}
function localGraph(subject){const suggested=params().get('suggestions')!=='0';let edges=index.edges.filter(e=>e.status!=='rejected'&&(e.status!=='suggested'||suggested)&&(e.source===subject.id||e.target===subject.id));edges.sort((a,b)=>(a.status==='suggested')-(b.status==='suggested')||(b.score||0)-(a.score||0));const neighbors=[...new Set(edges.map(e=>e.source===subject.id?e.target:e.source))].slice(0,12);const labels=new Map([subject.id,...neighbors].map(id=>[id,graphLines(index.subjects.find(s=>s.id===id).name)]));const nodeHeight=Math.max(40,...[...labels.values()].map(lines=>lines.length*16+20));const layout=circularLayout(neighbors.length,146,nodeHeight),graphHeight=layout.height,graphWidth=layout.width;const positions=new Map([[subject.id,layout.center],...neighbors.map((id,i)=>[id,layout.neighbors[i]])]);
  const linkLabel=e=>`${e.status==='suggested'?'Suggested ':e.status==='imported'?'Imported ': 'Reviewed '}${e.type==='broader'?(e.source===subject.id?'broader':'narrower'):e.type==='narrower'?(e.source===subject.id?'narrower':'broader'):'related'}${e.score!==undefined?' · overlap '+(e.score*100).toFixed(1)+'%':''}`;
  return `<h2>Connected subjects</h2>${neighbors.length?`<div class="graph-scroll"><svg class="subject-graph" viewBox="0 0 ${graphWidth} ${graphHeight}" width="${graphWidth}" height="${graphHeight}" style="height:auto;aspect-ratio:${graphWidth}/${graphHeight}" role="group" aria-label="Local subject graph. Activate a neighboring subject to explore it.">${edges.filter(e=>positions.has(e.source)&&positions.has(e.target)).map(e=>{const [x1,y1]=positions.get(e.source),[x2,y2]=positions.get(e.target);return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="var(--graph-edge)" ${e.status==='suggested'?'stroke-dasharray="5 5"':''}><title>${esc(linkLabel(e))}</title></line>`;}).join('')}${[subject.id,...neighbors].map(id=>{const s=index.subjects.find(s=>s.id===id),[x,y]=positions.get(id);return `<a href="${esc(url({subject:id,page:null,author:null,volume:null,availability:null}))}" aria-label="${esc(s.name)}"><title>${esc(s.name)}</title><rect x="${x-73}" y="${y-nodeHeight/2}" width="146" height="${nodeHeight}" rx="5" style="${colorStyle(s)};fill:var(--subject-bg)" stroke="var(--rule)"/><text x="${x}" y="${y+4}" text-anchor="middle" style="${colorStyle(s)};fill:var(--subject-color)">${labels.get(id).map((line,i)=>`<tspan x="${x}" y="${y-(labels.get(id).length-1)*8+4+i*16}">${esc(line)}</tspan>`).join('')}</text></a>`;}).join('')}</svg></div>`:'<p class="graph-empty">No connections to display for this subject yet.</p>'}`;
}
function editor(){const options=index.subjects.map(s=>`<option value="${s.id}" style="${colorStyle(s)};color:var(--subject-color);background:var(--subject-bg)">${esc(s.name)}</option>`).join('');return `<details class="editor-controls"><summary>Editorial workspace · decisions stay local until exported</summary><p>Confirm or reject selection mappings below. Add conceptual links here, or accept/reject an existing suggestion using the same endpoints and type.</p><label>Other subject <select id="edge-target">${options}</select></label><label>Relationship <select id="edge-type"><option>related</option><option>broader</option><option>narrower</option></select></label><label>Decision <select id="edge-status"><option value="accepted">Accept</option><option value="rejected">Reject</option></select></label><label>Editorial note <input id="edge-note" placeholder="Reason or supporting source"></label><button id="save-edge">Save connection decision</button> <button id="export-edits">Export decisions</button><label>Load existing decisions <input id="import-edits" type="file" accept="application/json,.json"></label><p id="editor-result" role="status"></p><details id="decision-preview-panel"><summary>Inspect or copy current decisions</summary><label>Decisions JSON<textarea id="decision-preview" readonly>${esc(JSON.stringify(getDraft(),null,2))}</textarea></label></details></details>`;}
function reviewHtml(s){return `<details class="subject-review"><summary>Review ${esc(s.status)} mapping · ${s.candidates.length} candidates</summary><p>${esc(s.reason||'Compare the proposed wording and source context before confirming.')}</p>${s.candidateSourcesTruncated||s.candidateLocationsTruncated?'<p>Candidate search was bounded; additional alternatives may exist.</p>':''}${s.candidates.map((c,i)=>`<details><summary>Candidate ${i+1}: ${esc(c.source)} · ${Math.round(c.score*100)}% · ${esc(c.method)}</summary><p>${esc(c.evidence||'Editorial mapping')}</p>${c.ranges.map(r=>`<p>Paragraph ${r.paragraph}, characters ${r.start}–${r.end}: ${esc(r.text)}</p>`).join('')}<a href="./?id=${encodeURIComponent(c.source)}#p-en-${c.ranges[0]?.paragraph||1}" target="_blank" rel="noopener">Inspect source in a new tab</a><button data-candidate="${i}" data-selection="${s.id}">Use this candidate in editor</button></details>`).join('')}<label>Mapping JSON (source, version, ranges; offsets are zero-based, end-exclusive)<textarea id="edit-${s.id}" spellcheck="false">${esc(JSON.stringify(s.candidates[0]||{source:'',version:'',ranges:[]},null,2))}</textarea></label><button data-confirm="${s.id}">Confirm mapping</button><button data-reject="${s.id}">Reject mapping</button></details>`;}
function graph(subject){return graphShell(params().get('graph')==='global'?'':localGraph(subject).replace('<h2>Connected subjects</h2>',''),params().get('graph')==='global');}
async function render(){
  disposeGraph();
  const token=++epoch,activeId=document.activeElement?.id;try{if(!params().get('subject')){const initial=index.subjects.find(s=>s.name==='oneness; unity of religion');if(initial)history.replaceState({},'',url({subject:initial.id})+location.hash);}directory();const p=params(),subject=index.subjects.find(s=>s.id===p.get('subject'));
    if(!subject){$('subject-content').innerHTML=`<h2>Browse ${index.subjects.length} subjects</h2><p>Choose a subject from the directory to explore its passages and connections.</p><p>${index.report.selections.toLocaleString()} selections imported; ${index.report.passages.toLocaleString()} distinct matched passages.</p><p class="subject-note">Source wording and existing subject associations are retained. Excerpts without a linked source ID appear after linked passages.</p>`;return;}
    $('subject-content').innerHTML='<p role="status">Opening selected passages…</p>';
    const data=await loadCompressed(new URL(`subjects/${subject.id}.json.gz`,base));if(token!==epoch)return;selected=data;document.title=subject.name+' · Subject view';
    const review=p.get('review')==='1';let rows=review?[...data.selections]:publicSelections(data.selections,data.sources);
    if(review){const status=p.get('status')||'pending';rows=rows.filter(s=>status==='all'||(status==='pending'?['approximate','ambiguous','unmatched'].includes(s.status):s.status===status));}
    if(review)rows.sort((a,b)=>compareSelections(a,b,data.sources));
    const size=10,pages=Math.max(1,Math.ceil(rows.length/size)),linkedIndex=rows.findIndex(s=>'#selection-'+s.id===location.hash),page=linkedIndex>=0?Math.floor(linkedIndex/size)+1:Math.min(pages,Math.max(1,parseInt(p.get('page'))||1)),visible=rows.slice((page-1)*size,page*size);
    $('subject-content').innerHTML=`<h2 class="subject-heading" tabindex="-1"><span class="subject-label" style="${colorStyle(subject)}">${esc(subject.name)}</span></h2>${graph(subject)}${review?editor():''}<h2>Selected passages</h2>${data.unavailable?'<p class="graph-empty" role="status">Selections unavailable. The supplied source URL could not be retrieved. This subject is retained in the directory; a corrected source URL is needed to import its passages.</p>':''}${review?'<div class="subject-filters"></div>':''}<p role="status">${rows.length.toLocaleString()} selections · page ${page} of ${pages}</p>${review&&data.notices.length?'<p class="subject-note">The selection source includes research notices; expand selection provenance to inspect them.</p>':''}${passageControls()}<div id="passage-results" class="passage-reader ${review?'':'continuous-passages'}"></div><div class="subject-pagination"><button id="subject-prev" ${page===1?'disabled':''}>← Previous</button><span>${page} / ${pages}</span><button id="subject-next" ${page===pages?'disabled':''}>Next →</button></div>`;
    disposeGraph=mountGraph(document.querySelector('.graph-panel'),{index,subject,global:p.get('graph')==='global',lines:graphLines,url,suggestions:p.get('suggestions')!=='0',onView:async view=>{await go({graph:view==='global'?'global':null});document.querySelector(`[data-graph-view="${view}"]`)?.focus({preventScroll:true});}});
    if(review){document.querySelector('.subject-filters').insertAdjacentHTML('afterbegin',`<label>Match status<select id="passage-status">${[['pending','Needs review'],['all','All statuses'],['approximate','Approximate'],['ambiguous','Ambiguous'],['unmatched','Unmatched'],['exact','Exact'],['normalized','Normalized'],['confirmed','Confirmed'],['rejected','Rejected']].map(([value,label])=>`<option value="${value}" ${(p.get('status')||'pending')===value?'selected':''}>${label}</option>`).join('')}</select></label>`);$('passage-status').onchange=e=>go({status:e.target.value,page:null});}
    $('subject-prev').onclick=()=>go({page:page-1});$('subject-next').onclick=()=>go({page:page+1});
    let savedReading={};try{savedReading=JSON.parse(localStorage.getItem('pi-reading')||'{}')||{};}catch{}
    const reading=readingPreferences(params(),savedReading);
    const rememberReading=next=>{
      try{localStorage.setItem('pi-reading',JSON.stringify(next));}catch{}
      history.replaceState({},'',url({mode:next.mode,size:Math.round(next.scale*100)})+location.hash);
      directory();
      for(const a of document.querySelectorAll('.subject-graph a')){const u=new URL(a.href.baseVal||a.getAttribute('href'),location.href);u.searchParams.set('mode',next.mode);u.searchParams.set('size',Math.round(next.scale*100));a.setAttribute('href',u.pathname+u.search+u.hash);}
    };
    wirePassageReading($('subject-content'),reading,rememberReading);
    if(review)wireEditor(subject);
    for(const s of visible){let html='',r,c=s.candidates[0];if(s.passage){r=await record(c.source);if(token!==epoch)return;}
      html+=`<article class="subject-passage" id="selection-${s.id}">`;
      if(review)html+=`<div class="passage-meta">${esc(s.status)} · selection ${s.provenance.selectionParagraph}</div><blockquote>${esc(s.excerpt)}</blockquote>`;
      if(!review&&!r)html+=unlinkedPassage(s);
      if(r){const nums=[...new Set(c.ranges.map(range=>range.paragraph))];
        const reference=passageCitation(r,`./?id=${encodeURIComponent(r.id)}&passage=${encodeURIComponent(s.passage)}&subject=${encodeURIComponent(subject.id)}#p-en-${nums[0]}`);
        html+=nums.map((n,i)=>{const citation=i===nums.length-1?' '+reference:'';
          return `<div class="passage-pair"><div class="passage-translation" aria-label="English paragraph ${n}"><p>${highlight(r.en.paragraphs[n-1]?.plain||'',c.ranges.filter(range=>range.paragraph===n))}${citation}</p></div><div class="passage-original" aria-label="Original paragraph ${n}">${r.original.paragraphs[n-1]?.plain?`<p dir="rtl">${esc(r.original.paragraphs[n-1].plain)}${citation}</p>`:`<p dir="ltr" lang="en">Original text unavailable${citation}</p>`}</div></div>`;
        }).join('');}
      if(review)html+=`<details><summary>Selection provenance</summary><p>${esc(s.original)}</p><p class="passage-meta">Quote ${esc(s.provenance.quoteId)} · block ${s.provenance.blockPosition}${s.provenance.segment?" · segment "+s.provenance.segment:""} · ${esc(s.provenance.subjectFilename)} row ${s.provenance.subjectRow} · source ID ${esc(s.suppliedIds.join(', ')||'not supplied')}</p>${s.provenance.sourceBlockRaw?`<details><summary>Original combined source block</summary><pre class="provenance-raw">${esc(s.provenance.sourceBlockRaw)}</pre></details>`:""}${data.notices.filter(n=>n.quoteId===s.provenance.quoteId).map(n=>`<p class="subject-note">${esc(n.text)}</p>`).join('')}</details>${reviewHtml(s)}`;
      html+='</article>';
      $('passage-results').insertAdjacentHTML('beforeend',html);
    }
    if(!visible.length)$('passage-results').innerHTML=subject.selections===0&&!subject.unavailable?'<p>No selections are assigned directly to this subject. Explore its connected subjects.</p>':'<p>No selections to display.</p>';
    if(review){wireSelections();wireLookups();}(document.getElementById(activeId)||document.querySelector('.subject-heading'))?.focus({preventScroll:true});if(location.hash)document.getElementById(location.hash.slice(1))?.scrollIntoView({block:'start'});
  }catch(e){if(token===epoch)$('subject-content').innerHTML=`<h2>Subject unavailable</h2><p>${esc(e.message)}</p><button id="subject-retry">Try again</button>`;if($('subject-retry'))$('subject-retry').onclick=render;}
}
function wireLookups(){for(const section of document.querySelectorAll('.subject-review')){const id=section.closest('article').id.slice('selection-'.length),s=selected.selections.find(s=>s.id===id);const holder=document.createElement('div');holder.className='source-lookup';holder.innerHTML=`<label>Source filename ID <input id="lookup-source-${id}" value="${esc(s.suppliedIds[0]||'')}"></label><label>Paragraph number <input id="lookup-number-${id}" type="number" min="1" value="1"></label><button type="button">Load source paragraph into editor</button><p role="status"></p>`;section.querySelector('textarea').parentElement.before(holder);holder.querySelector('button').onclick=async()=>{try{const source=$('lookup-source-'+id).value.trim().replace(/\.txt$/i,''),n=Number($('lookup-number-'+id).value);if(!/^[\p{L}\p{N}_ ()-]+$/u.test(source))throw Error('Invalid source filename');const r=await record(source),p=r.en.paragraphs[n-1];if(!p)throw Error('English paragraph unavailable.');$('edit-'+id).value=JSON.stringify({source,version:r.enVersion,ranges:[{paragraph:n,paragraphId:`${source}@${r.enVersion}:en:${n}`,start:0,end:p.plain.length,text:p.plain}],method:'editorial',score:1,evidence:'Manual source lookup'},null,2);holder.querySelector('p').textContent='Source paragraph loaded. Adjust start/end offsets to the selected wording before confirming.';}catch(e){holder.querySelector('p').textContent=e.message;}};}}
function wireEditor(subject){$('save-edge').onclick=()=>{try{const d=getDraft(),edge={source:subject.id,target:$('edge-target').value,type:$('edge-type').value,status:$('edge-status').value,note:$('edge-note').value};if(edge.source===edge.target)throw Error('Choose a different subject.');d.relationships=d.relationships.filter(e=>relationKey(e)!==relationKey(edge));d.relationships.push(edge);saveDraft(d);}catch(e){$('editor-result').textContent=e.message;}};$('export-edits').onclick=()=>{$('decision-preview').value=JSON.stringify(getDraft(),null,2);$('decision-preview-panel').open=true;const a=document.createElement('a'),blob=URL.createObjectURL(new Blob([JSON.stringify(getDraft(),null,2)],{type:'application/json'}));a.href=blob;a.download='subject-edits.json';a.click();setTimeout(()=>URL.revokeObjectURL(blob),1000);};$('import-edits').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(d.format!==1||!d.matches||!Array.isArray(d.relationships))throw Error('Invalid decisions file.');saveDraft(d);}catch(e){$('editor-result').textContent=e.message;}};}
function wireSelections(){document.querySelectorAll('[data-candidate]').forEach(b=>b.onclick=()=>{$('edit-'+b.dataset.selection).value=JSON.stringify(selected.selections.find(s=>s.id===b.dataset.selection).candidates[Number(b.dataset.candidate)],null,2);});for(const action of ['confirm','reject'])document.querySelectorAll('[data-'+action+']').forEach(b=>b.onclick=async()=>{try{const id=b.dataset[action],d=getDraft();if(action==='reject')d.matches[id]={status:'rejected'};else{const c=JSON.parse($('edit-'+id).value),r=await record(c.source);if(!c.ranges?.length)throw Error('At least one range is required.');if(c.version!==r.enVersion)throw Error('Source version differs. Use the version from a current candidate.');for(const range of c.ranges){const p=r.en.paragraphs[range.paragraph-1];if(!p||!Number.isInteger(range.start)||!Number.isInteger(range.end)||range.start<0||range.end<=range.start||range.end>p.plain.length)throw Error('Invalid paragraph or character range.');range.text=p.plain.slice(range.start,range.end);range.paragraphId=`${c.source}@${c.version}:en:${range.paragraph}`;}d.matches[id]={status:'confirmed',candidate:c};}saveDraft(d);b.textContent='Decision saved';}catch(e){$('editor-result').textContent=e.message;}});}
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a||a.getAttribute('href').startsWith('#')||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const u=new URL(a.getAttribute('href'),location.href);if(u.origin===location.origin&&u.pathname===location.pathname){e.preventDefault();history.pushState({},'',u);render();}});
window.addEventListener('popstate',render);
try{await document.fonts.load('14px "EB Garamond"');const response=await fetch('./stats.json',{cache:'no-cache'});if(!response.ok)throw Error('Collection manifest unavailable');const stats=await response.json();$('about-stats').textContent=`The collection contains ${stats.records.toLocaleString()} catalogue records, including ${stats.pairs.toLocaleString()} texts with both language versions. ${stats.metadataOnly.toLocaleString()} records have metadata only.`;base=new URL(stats.dataset,location.href);index=await loadCompressed(new URL('subjects/index.json.gz',base));index.subjects.sort((a,b)=>a.name.localeCompare(b.name));const orderResponse=await fetch('./subject-order.json');if(!orderResponse.ok)throw Error('Subject order unavailable');const orderData=await orderResponse.json();thematicGroups=orderData.groups;$('subject-query').oninput=directory;$('subject-order').onchange=()=>go({order:$('subject-order').value==='thematic'?null:'alphabetical'});$('subject-total').textContent=index.subjects.length.toLocaleString();$('selection-total').textContent=index.report.selections.toLocaleString();$('subject-status').hidden=true;await render();}catch(e){$('subject-status').hidden=false;$('subject-status').className='subject-status-error';$('subject-status').textContent=e.message+' Reload to try again.';}
