import {recordFilename} from './record-file.mjs';
import {loadCompressed} from './data.mjs';
import {escapeHtml as esc} from './text.mjs';
import {relationKey} from './subject-relations.mjs';
const $=id=>document.getElementById(id),params=()=>new URLSearchParams(location.search);
let index,base,selected,epoch=0,zoom=1;const cache=new Map();
let canonicalOrder=new Map();
function colorStyle(subject){const c=/^#[a-f\d]{6}$/i.test(subject?.color)?subject.color:'#203a32';return `--subject-color:${c};--subject-bg:#fffefa`;}
function subjectLink(id,label){const s=index.subjects.find(s=>s.id===id);return s?`<a class="subject-label subject-link" style="${colorStyle(s)}" href="${esc(url({subject:id,page:null,author:null,volume:null,availability:null}))}">${esc(label||s.name)}</a>`:esc(id);}
function url(changes={}){const p=params();for(const [k,v] of Object.entries(changes))v===null||v===''?p.delete(k):p.set(k,v);return './subjects.html'+(p.size?'?'+p:'');}
function go(changes){history.pushState({},'',url(changes));render();}
function directory(){const q=$('subject-query').value.toLowerCase(),order=params().get('order')==='canonical'?'canonical':'alphabetical';$('subject-order').value=order;const rows=index.subjects.filter(s=>s.name.toLowerCase().includes(q)).sort((a,b)=>order==='canonical'?(canonicalOrder.get(a.name)??Infinity)-(canonicalOrder.get(b.name)??Infinity)||a.name.localeCompare(b.name):a.name.localeCompare(b.name));$('subject-count').textContent=`${rows.length} of ${index.subjects.length} subjects`;$('subject-list').innerHTML=rows.map(s=>`<a class="subject-label" style="${colorStyle(s)}" ${s.id===params().get('subject')?'aria-current="true"':''} href="${esc(url({subject:s.id,page:null,author:null,volume:null,availability:null}))}">${esc(s.name)} <small>(${s.matched??0})</small></a>`).join('');}
async function record(id){if(cache.has(id))return cache.get(id);const promise=loadCompressed(new URL(`data/${encodeURIComponent(recordFilename(id))}`,base)).catch(e=>{cache.delete(id);throw e;});cache.set(id,promise);if(cache.size>20)cache.delete(cache.keys().next().value);return promise;}
function highlight(text,ranges){let result='',end=0;const merged=[];for(const r of [...ranges].sort((a,b)=>a.start-b.start)){if(merged.length&&r.start<=merged.at(-1).end)merged.at(-1).end=Math.max(merged.at(-1).end,r.end);else merged.push({...r});}for(const r of merged){result+=esc(text.slice(end,r.start))+`<mark>${esc(text.slice(r.start,r.end))}</mark>`;end=r.end;}return result+esc(text.slice(end));}
function getDraft(){try{return JSON.parse(localStorage.getItem('pi-subject-edits')||'{"format":1,"matches":{},"relationships":[]}');}catch{return {format:1,matches:{},relationships:[]};}}
function saveDraft(draft){localStorage.setItem('pi-subject-edits',JSON.stringify(draft));if($('decision-preview'))$('decision-preview').value=JSON.stringify(draft,null,2);$('editor-result').textContent='Saved in this browser. Export decisions and import them into the project to publish.';}
function graph(subject){const suggested=params().get('suggestions')!=='0';let edges=index.edges.filter(e=>e.status!=='rejected'&&(e.status!=='suggested'||suggested)&&(e.source===subject.id||e.target===subject.id));edges.sort((a,b)=>(a.status==='suggested')-(b.status==='suggested')||(b.score||0)-(a.score||0));const neighbors=[...new Set(edges.map(e=>e.source===subject.id?e.target:e.source))].slice(0,12);const positions=new Map([[subject.id,[400,175]]]);neighbors.forEach((id,i)=>{const side=i%2,row=Math.floor(i/2);const rows=Math.ceil(neighbors.length/2);positions.set(id,[side?680:120,rows===1?175:30+row*290/(rows-1)]);});
  const linkLabel=e=>`${e.status==='suggested'?'Suggested ':e.status==='imported'?'Imported ': 'Reviewed '}${e.type==='broader'?(e.source===subject.id?'broader':'narrower'):e.type==='narrower'?(e.source===subject.id?'narrower':'broader'):'related'}${e.score!==undefined?' · overlap '+(e.score*100).toFixed(1)+'%':''}`;
  return `<h2>Connected subjects</h2><div class="graph-controls"><label><input id="show-suggestions" type="checkbox" ${suggested?'checked':''}> Include suggested connections</label><button id="graph-in" aria-label="Zoom in on graph">+</button><button id="graph-out" aria-label="Zoom out of graph">−</button><button id="graph-reset">Reset graph</button></div><p class="graph-key"><span>Solid: imported or reviewed</span><span>Dashed: suggested overlap</span></p>${neighbors.length?`<div class="graph-scroll"><svg class="subject-graph" viewBox="0 0 800 350" role="group" aria-label="Local subject graph. Activate a neighboring subject to explore it.">${edges.filter(e=>positions.has(e.source)&&positions.has(e.target)).map(e=>{const [x1,y1]=positions.get(e.source),[x2,y2]=positions.get(e.target);return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#8b9b8e" ${e.status==='suggested'?'stroke-dasharray="5 5"':''}><title>${esc(linkLabel(e))}</title></line>`;}).join('')}${[subject.id,...neighbors].map(id=>{const s=index.subjects.find(s=>s.id===id),[x,y]=positions.get(id);return `<a href="${esc(url({subject:id,page:null,author:null,volume:null,availability:null}))}" aria-label="${esc(s.name)}"><title>${esc(s.name)}</title><rect x="${x-103}" y="${y-20}" width="206" height="40" rx="5" style="${colorStyle(s)};fill:var(--subject-bg)" stroke="#dddfd4"/><text x="${x}" y="${y+4}" text-anchor="middle" fill="${s.color}">${esc(s.name.length>29?s.name.slice(0,27)+'…':s.name)}</text></a>`;}).join('')}</svg></div>`:'<p class="graph-empty">No imported or reviewed connections for this subject yet. Include suggestions to explore textual overlap, or add a connection in the editorial workspace.</p>'}<div class="related-links">${edges.slice(0,12).map(e=>`<span>${subjectLink(e.source===subject.id?e.target:e.source)}<br><small>${esc(linkLabel(e))}</small></span>`).join('')}</div>${edges.length>12?`<details><summary>Show ${edges.length-12} more connections</summary><div class="related-links">${edges.slice(12).map(e=>`<span>${subjectLink(e.source===subject.id?e.target:e.source)}<br><small>${esc(linkLabel(e))}</small></span>`).join('')}</div></details>`:''}`;
}
function editor(){const options=index.subjects.map(s=>`<option value="${s.id}" style="${colorStyle(s)};color:var(--subject-color);background:var(--subject-bg)">${esc(s.name)}</option>`).join('');return `<details class="editor-controls"><summary>Editorial workspace · decisions stay local until exported</summary><p>Confirm or reject selection mappings below. Add conceptual links here, or accept/reject an existing suggestion using the same endpoints and type.</p><label>Other subject <select id="edge-target">${options}</select></label><label>Relationship <select id="edge-type"><option>related</option><option>broader</option><option>narrower</option></select></label><label>Decision <select id="edge-status"><option value="accepted">Accept</option><option value="rejected">Reject</option></select></label><label>Editorial note <input id="edge-note" placeholder="Reason or supporting source"></label><button id="save-edge">Save connection decision</button> <button id="export-edits">Export decisions</button><label>Load existing decisions <input id="import-edits" type="file" accept="application/json,.json"></label><p id="editor-result" role="status"></p><details id="decision-preview-panel"><summary>Inspect or copy current decisions</summary><label>Decisions JSON<textarea id="decision-preview" readonly>${esc(JSON.stringify(getDraft(),null,2))}</textarea></label></details></details>`;}
function reviewHtml(s){return `<details class="subject-review"><summary>Review ${esc(s.status)} mapping · ${s.candidates.length} candidates</summary><p>${esc(s.reason||'Compare the proposed wording and source context before confirming.')}</p>${s.candidateSourcesTruncated||s.candidateLocationsTruncated?'<p>Candidate search was bounded; additional alternatives may exist.</p>':''}${s.candidates.map((c,i)=>`<details><summary>Candidate ${i+1}: ${esc(c.source)} · ${Math.round(c.score*100)}% · ${esc(c.method)}</summary><p>${esc(c.evidence||'Editorial mapping')}</p>${c.ranges.map(r=>`<p>Paragraph ${r.paragraph}, characters ${r.start}–${r.end}: ${esc(r.text)}</p>`).join('')}<a href="./?id=${encodeURIComponent(c.source)}#p-en-${c.ranges[0]?.paragraph||1}" target="_blank" rel="noopener">Inspect source in a new tab</a><button data-candidate="${i}" data-selection="${s.id}">Use this candidate in editor</button></details>`).join('')}<label>Mapping JSON (source, version, ranges; offsets are zero-based, end-exclusive)<textarea id="edit-${s.id}" spellcheck="false">${esc(JSON.stringify(s.candidates[0]||{source:'',version:'',ranges:[]},null,2))}</textarea></label><button data-confirm="${s.id}">Confirm mapping</button><button data-reject="${s.id}">Reject mapping</button></details>`;}
async function render(){
  const token=++epoch,activeId=document.activeElement?.id;try{directory();const p=params(),subject=index.subjects.find(s=>s.id===p.get('subject'));
    if(!subject){$('subject-content').innerHTML=`<h2>Browse ${index.subjects.length} subjects</h2><p>Choose a subject from the directory to explore its passages and connections.</p><p>${index.report.selections.toLocaleString()} selections imported; ${index.report.passages.toLocaleString()} distinct matched passages.</p><p class="subject-note">Source wording and existing subject associations are retained. Approximate, ambiguous, and unmatched selections remain available for editorial review.</p>`;return;}
    $('subject-content').innerHTML='<p role="status">Opening selected passages…</p>';
    const data=await loadCompressed(new URL(`subjects/${subject.id}.json.gz`,base));if(token!==epoch)return;selected=data;document.title=subject.name+' · Subject view';
    const review=p.get('review')==='1',original=p.get('original')!=='0';let rows=data.selections.filter(s=>review||s.passage);
    const sourceFor=s=>data.sources[s.candidates[0]?.source||s.suppliedIds[0]]||{};
    const filterOptions=key=>[...new Set(rows.map(s=>sourceFor(s)[key]).filter(Boolean))].sort().map(v=>`<option ${p.get(key)===v?'selected':''}>${esc(v)}</option>`).join('');
    const filters=`<div class="subject-filters"><label>Author<select id="passage-author"><option value="">All authors</option>${filterOptions('author')}</select></label><label>Volume<select id="passage-volume"><option value="">All volumes</option>${filterOptions('volume')}</select></label><label>Source availability<select id="passage-availability"><option value="">All sources</option><option value="parallel" ${p.get('availability')==='parallel'?'selected':''}>Original available</option><option value="english" ${p.get('availability')==='english'?'selected':''}>English only</option></select></label><div>Display<label><input id="show-original" type="checkbox" ${original?'checked':''}> Show Persian/Arabic</label></div></div>`;
    rows=rows.filter(s=>{const r=sourceFor(s);return (!p.get('author')||r.author===p.get('author'))&&(!p.get('volume')||r.volume===p.get('volume'))&&(!p.get('availability')||(p.get('availability')==='parallel'?r.hasOriginal:!r.hasOriginal));});
    if(review){const status=p.get('status')||'pending';rows=rows.filter(s=>status==='all'||(status==='pending'?['approximate','ambiguous','unmatched'].includes(s.status):s.status===status));}
    rows.sort((a,b)=>(a.candidates[0]?.source||'~').localeCompare(b.candidates[0]?.source||'~')||(a.candidates[0]?.ranges[0]?.paragraph||0)-(b.candidates[0]?.ranges[0]?.paragraph||0));
    const size=10,pages=Math.max(1,Math.ceil(rows.length/size)),linkedIndex=rows.findIndex(s=>'#selection-'+s.id===location.hash),page=linkedIndex>=0?Math.floor(linkedIndex/size)+1:Math.min(pages,Math.max(1,parseInt(p.get('page'))||1)),visible=rows.slice((page-1)*size,page*size);
    $('subject-content').innerHTML=`<h2 class="subject-heading" tabindex="-1"><span class="subject-label" style="${colorStyle(subject)}">${esc(subject.name)}</span></h2><div class="subject-summary"><span>${subject.matched.toLocaleString()} matched selections</span><span>${(subject.selections-subject.matched).toLocaleString()} awaiting review</span><a href="${esc(subject.url)}" target="_blank" rel="noopener">Selection provenance ↗</a></div>${graph(subject)}${review?editor():''}<h2>Selected passages</h2>${data.unavailable?'<p class="graph-empty" role="status">Selections unavailable. The supplied source URL could not be retrieved. This subject is retained in the directory; a corrected source URL is needed to import its passages.</p>':''}${filters}<p role="status">${rows.length.toLocaleString()} ${review?'selections':'matched selections'} · page ${page} of ${pages}</p><p class="subject-note">Original text is shown by the same paragraph number, without a claim of verified alignment. ${data.notices.length?'The selection source includes research notices; expand selection provenance to inspect them.':''}</p><div id="passage-results"></div><div class="subject-pagination"><button id="subject-prev" ${page===1?'disabled':''}>← Previous</button><span>${page} / ${pages}</span><button id="subject-next" ${page===pages?'disabled':''}>Next →</button></div>`;
    $('show-suggestions').onchange=e=>go({suggestions:e.target.checked?null:'0'});$('show-original').onchange=e=>go({original:e.target.checked?null:'0'});
    if(review){document.querySelector('.subject-filters').insertAdjacentHTML('afterbegin',`<label>Match status<select id="passage-status">${[['pending','Needs review'],['all','All statuses'],['approximate','Approximate'],['ambiguous','Ambiguous'],['unmatched','Unmatched'],['exact','Exact'],['normalized','Normalized'],['confirmed','Confirmed'],['rejected','Rejected']].map(([value,label])=>`<option value="${value}" ${(p.get('status')||'pending')===value?'selected':''}>${label}</option>`).join('')}</select></label>`);$('passage-status').onchange=e=>go({status:e.target.value,page:null});}
    for(const key of ['author','volume','availability'])$('passage-'+key).onchange=e=>go({[key]:e.target.value,page:null});
    $('subject-prev').onclick=()=>go({page:page-1});$('subject-next').onclick=()=>go({page:page+1});
    const zoomGraph=()=>{const svg=document.querySelector('.subject-graph');if(svg)svg.setAttribute('viewBox',`${400-400/zoom} ${175-175/zoom} ${800/zoom} ${350/zoom}`);};$('graph-in').onclick=()=>{zoom=Math.min(2,zoom+.2);zoomGraph();};$('graph-out').onclick=()=>{zoom=Math.max(.6,zoom-.2);zoomGraph();};$('graph-reset').onclick=()=>{zoom=1;zoomGraph();};
    if(review)wireEditor(subject);
    let previous='';for(const s of visible){let html='',r,c=s.candidates[0];if(s.passage){r=await record(c.source);if(token!==epoch)return;if(previous!==r.id){html+=`<h3 class="source-group-title">${esc(r.id)} · ${esc(r.title||r.author)}</h3>`;previous=r.id;}}
      html+=`<article class="subject-passage" id="selection-${s.id}"><div class="passage-meta">${esc(s.status)} · selection ${s.provenance.selectionParagraph}${r?' · '+esc(r.date||'Date not recorded'):''}</div><blockquote>${esc(s.excerpt)}</blockquote>`;
      if(r){const nums=[...new Set(c.ranges.map(range=>range.paragraph))];html+=nums.map(n=>`<div class="passage-pair"><div><small>English · paragraph ${n}</small><p>${highlight(r.en.paragraphs[n-1]?.plain||'',c.ranges.filter(range=>range.paragraph===n))}</p></div><div class="passage-original" ${original?'':'hidden'}><small>Original · paragraph ${n}</small><p dir="rtl">${esc(r.original.paragraphs[n-1]?.plain||'Original paragraph unavailable.')}</p></div></div>`).join('');html+=`<p><a href="./?id=${encodeURIComponent(r.id)}&passage=${s.passage}&subject=${subject.id}#p-en-${nums[0]}">Read in full source with highlights →</a> · <a href="${esc(url({subject:subject.id,page}))}#selection-${s.id}">Permanent selection link</a></p><p>Subjects: ${(s.otherSubjects||[]).map(id=>subjectLink(id)).join(' · ')}</p>`;}
      html+=`<details><summary>Selection provenance</summary><p>${esc(s.original)}</p><p class="passage-meta">Quote ${esc(s.provenance.quoteId)} · block ${s.provenance.blockPosition}${s.provenance.segment?" · segment "+s.provenance.segment:""} · ${esc(s.provenance.subjectFilename)} row ${s.provenance.subjectRow} · source ID ${esc(s.suppliedIds.join(', ')||'not supplied')}</p>${s.provenance.sourceBlockRaw?`<details><summary>Original combined source block</summary><pre class="provenance-raw">${esc(s.provenance.sourceBlockRaw)}</pre></details>`:""}${data.notices.filter(n=>n.quoteId===s.provenance.quoteId).map(n=>`<p class="subject-note">${esc(n.text)}</p>`).join('')}</details>${review?reviewHtml(s):''}</article>`;
      $('passage-results').insertAdjacentHTML('beforeend',html);
    }
    if(!visible.length)$('passage-results').innerHTML=subject.selections===0&&!subject.unavailable?'<p>No selections are assigned directly to this subject. Explore its connected subjects.</p>':'<p>No selections match these filters.</p>';
    if(review){wireSelections();wireLookups();}(document.getElementById(activeId)||document.querySelector('.subject-heading'))?.focus({preventScroll:true});if(location.hash)document.getElementById(location.hash.slice(1))?.scrollIntoView({block:'start'});
  }catch(e){if(token===epoch)$('subject-content').innerHTML=`<h2>Subject unavailable</h2><p>${esc(e.message)}</p><button id="subject-retry">Try again</button>`;if($('subject-retry'))$('subject-retry').onclick=render;}
}
function wireLookups(){for(const section of document.querySelectorAll('.subject-review')){const id=section.closest('article').id.slice('selection-'.length),s=selected.selections.find(s=>s.id===id);const holder=document.createElement('div');holder.className='source-lookup';holder.innerHTML=`<label>Source filename ID <input id="lookup-source-${id}" value="${esc(s.suppliedIds[0]||'')}"></label><label>Paragraph number <input id="lookup-number-${id}" type="number" min="1" value="1"></label><button type="button">Load source paragraph into editor</button><p role="status"></p>`;section.querySelector('textarea').parentElement.before(holder);holder.querySelector('button').onclick=async()=>{try{const source=$('lookup-source-'+id).value.trim().replace(/\.txt$/i,''),n=Number($('lookup-number-'+id).value);if(!/^[\p{L}\p{N}_ ()-]+$/u.test(source))throw Error('Invalid source filename');const r=await record(source),p=r.en.paragraphs[n-1];if(!p)throw Error('English paragraph unavailable.');$('edit-'+id).value=JSON.stringify({source,version:r.enVersion,ranges:[{paragraph:n,paragraphId:`${source}@${r.enVersion}:en:${n}`,start:0,end:p.plain.length,text:p.plain}],method:'editorial',score:1,evidence:'Manual source lookup'},null,2);holder.querySelector('p').textContent='Source paragraph loaded. Adjust start/end offsets to the selected wording before confirming.';}catch(e){holder.querySelector('p').textContent=e.message;}};}}
function wireEditor(subject){$('save-edge').onclick=()=>{try{const d=getDraft(),edge={source:subject.id,target:$('edge-target').value,type:$('edge-type').value,status:$('edge-status').value,note:$('edge-note').value};if(edge.source===edge.target)throw Error('Choose a different subject.');d.relationships=d.relationships.filter(e=>relationKey(e)!==relationKey(edge));d.relationships.push(edge);saveDraft(d);}catch(e){$('editor-result').textContent=e.message;}};$('export-edits').onclick=()=>{$('decision-preview').value=JSON.stringify(getDraft(),null,2);$('decision-preview-panel').open=true;const a=document.createElement('a'),blob=URL.createObjectURL(new Blob([JSON.stringify(getDraft(),null,2)],{type:'application/json'}));a.href=blob;a.download='subject-edits.json';a.click();setTimeout(()=>URL.revokeObjectURL(blob),1000);};$('import-edits').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(d.format!==1||!d.matches||!Array.isArray(d.relationships))throw Error('Invalid decisions file.');saveDraft(d);}catch(e){$('editor-result').textContent=e.message;}};}
function wireSelections(){document.querySelectorAll('[data-candidate]').forEach(b=>b.onclick=()=>{$('edit-'+b.dataset.selection).value=JSON.stringify(selected.selections.find(s=>s.id===b.dataset.selection).candidates[Number(b.dataset.candidate)],null,2);});for(const action of ['confirm','reject'])document.querySelectorAll('[data-'+action+']').forEach(b=>b.onclick=async()=>{try{const id=b.dataset[action],d=getDraft();if(action==='reject')d.matches[id]={status:'rejected'};else{const c=JSON.parse($('edit-'+id).value),r=await record(c.source);if(!c.ranges?.length)throw Error('At least one range is required.');if(c.version!==r.enVersion)throw Error('Source version differs. Use the version from a current candidate.');for(const range of c.ranges){const p=r.en.paragraphs[range.paragraph-1];if(!p||!Number.isInteger(range.start)||!Number.isInteger(range.end)||range.start<0||range.end<=range.start||range.end>p.plain.length)throw Error('Invalid paragraph or character range.');range.text=p.plain.slice(range.start,range.end);range.paragraphId=`${c.source}@${c.version}:en:${range.paragraph}`;}d.matches[id]={status:'confirmed',candidate:c};}saveDraft(d);b.textContent='Decision saved';}catch(e){$('editor-result').textContent=e.message;}});}
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a||a.getAttribute('href').startsWith('#')||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const u=new URL(a.getAttribute('href'),location.href);if(u.origin===location.origin&&u.pathname===location.pathname){e.preventDefault();history.pushState({},'',u);zoom=1;render();}});
window.addEventListener('popstate',render);
try{const response=await fetch('./stats.json',{cache:'no-cache'});if(!response.ok)throw Error('Collection manifest unavailable');const stats=await response.json();base=new URL(stats.dataset,location.href);index=await loadCompressed(new URL('subjects/index.json.gz',base));index.subjects.sort((a,b)=>a.name.localeCompare(b.name));const orderResponse=await fetch('./subject-order.json');if(!orderResponse.ok)throw Error('Subject order unavailable');const orderData=await orderResponse.json();canonicalOrder=new Map(orderData.subjects.map((name,i)=>[name,i]));$('subject-query').oninput=directory;$('subject-order').onchange=()=>go({order:$('subject-order').value==='canonical'?'canonical':null});$('subject-status').textContent=`${index.subjects.length} subjects · ${index.report.selections.toLocaleString()} selections · source snapshot ${index.report.snapshotDate.slice(0,10)}`;await render();}catch(e){$('subject-status').className='subject-status-error';$('subject-status').textContent=e.message+' Reload to try again.';}
